### ISSUE TITLE
[Request] Add TV Shows section

### ISSUE THREAD

**Issue by Edydaoud** [surgeharb/open-movies#1]
You got a great website for downloading Movies, are there any plans to add TV Shows section the website?

**Comment by surgeharb** [comment]
Thank you for the request, this feature is on our timeline. 

Keep up for new changes!
Cheers

**Comment by surgeharb** [comment]
We just released an update featuring Movies/Series(TV Shows) to the header's navigation bar dropdown. Feel free to submit any further issues that you face :)
